flush ruleset

table inet filter {
  chain input {
    type filter hook input priority 0; policy drop;
    
    iif "lo" accept
    ct state established, related accept    
  }
  chain output {
    type filter hook output priority 0; policy drop;
    oif "lo" accept
    ct state established,related accept

    ip daddr 127.0.0.11 accept
    
    udp dport 53 accept
    tcp dport 53 accept
    meta skuid 31 tcp dport 443 accept
  }
  chain forward {
    type filter hook forward priority 0; policy drop;
  }
}
